### ISSUE TITLE
Start again

### ISSUE THREAD

**Issue by Gblumentals** [jitta/Natural-Language-Generation#3]
Guy, this library is a mess. It's really confusing. All your examples have practically the same outputs AND NONE of the functions have a description of what they do, in place you wrote different variable names to go with each invocation, which is visible in the example, but clarifies all most nothing of the difference... Not cool

**Comment by withlovee** [comment]
Thank you for your suggestion. I'll try to improve it. My point of the README is to be a guideline for people at Jitta of how to use the module. And I forgot to point out what my module really does (The point was to compare between the old json data and new json data and generate some sentences to inform the users.)

I'm a beginner at this kind of thing (open-source stuff) and I was an intern developing this module for people at Jitta. You can give me some detailed suggestion at happierv@gmail.com. I'd be really appreciated! +1

**Comment by hunt** [comment]
@Gblumentals Hey! I think the way you do, this is called "NOT COOL" at all. First the module doing great on what we expected and @withlovee open source code for other to hack or do something as them wish (dont need to reinvent the whole wheel)

The polite way or the good manner way you can just tell "Please rewrite the README so I can understand it or easy to know what this module can do" this is the way of people in the opensource world do, give comment, give feedback and cheer them up! She open the code for FREE and this is not the way to support what she did.

It will be awesome if you don't do something like this to other open source projects.
